### ISSUE TITLE
sys.exit

### ISSUE THREAD

**Issue by typemytype** [cjdunn/RoboFontExtensions#6]
https://github.com/cjdunn/RoboFontExtensions/blob/master/Delorean/Delorean.roboFontExt/lib/delorean.py#L464

calling `sys.exit()` inside a run loop is not oke, please remove this as this quits RoboFont instantly.

**Comment by cjdunn** [comment]
@typemytype Thanks for letting me know that this is a problem. I tried using `return` instead of `sys.exit()` but it wouldn't work unless I put all of those checks into a function. Here's what it looks like now: https://github.com/cjdunn/RoboFontExtensions/pull/7

Is this the best way to terminate the script when these conditions aren't met? Or is there something else you recommend?

**Comment by typemytype** [comment]
already looks beter!! 
or you could call the dialog from inside the if statement

**Comment by cjdunn** [comment]
OK, merged
